{\rtf1\ansi\ansicpg1252\cocoartf2761
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red193\green193\blue193;\red24\green24\blue24;\red70\green137\blue204;
\red67\green192\blue160;\red194\green126\blue101;}
{\*\expandedcolortbl;;\cssrgb\c80000\c80000\c80000;\cssrgb\c12157\c12157\c12157;\cssrgb\c33725\c61176\c83922;
\cssrgb\c30588\c78824\c69020;\cssrgb\c80784\c56863\c47059;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 [\cf4 \strokec4 gmail\cf2 \strokec2 ]\cb1 \
\pard\pardeftab720\partightenfactor0
\cf5 \cb3 \strokec5 client_id\cf2 \strokec2  = \cf6 \strokec6 "783954157104-6dki1sfpvhqc838r239f180vq5m369b1.apps.googleusercontent.com"\cf2 \cb1 \strokec2 \
\cf5 \cb3 \strokec5 client_secret\cf2 \strokec2  = \cf6 \strokec6 "GOcSPX-h3PU4hT7Vj_IujJj_MrIHrtE50TX"}
